### ISSUE TITLE
根据城市分库分表

### ISSUE THREAD

**Issue by wzxit** [shardingjdbc/sharding-jdbc-doc#1]
分库是根据不同区域，如华北、华东....，每个库里面有不通的表（如A库（item_bj,item_tj）,B库（item_sh））。但是我创建TableRule 时候 必须每个库必须有所有城市的分表才可以，否则聚合查询报错。
有没有解决办法呢？多谢

**Comment by terrymanu** [comment]
这个repo仅用于文档
