### ISSUE TITLE
There is something wrong with the last example of "Data Node Configuration"

### ISSUE THREAD

**Issue by zavch** [shardingjdbc/sharding-jdbc-doc#538]
The last example of ["Data Node Configuration" ](https://shardingsphere.apache.org/document/current/en/features/sharding/concept/inline-expression/#data-node-configuration):
`db->${0..1}.t_order_0$->{0..9}, db$->{0..1}.t_order_$->{10..20}`
Need to be modified to：
`db$->{0..1}.t_order_0$->{0..9}, db$->{0..1}.t_order_$->{10..20}`

**Comment by terrymanu** [comment]
Can you submit a pull request to fix it?
