### ISSUE TITLE
 README and Contributing.md files not included.

### ISSUE THREAD

**Issue by AnshuTrivedi** [shardingjdbc/sharding-jdbc-doc#544]
Issue:
I felt difficulty in understanding what project is about and how to contribute if want.

Suggestion:
Please consider including README and Contributing.md if possible.

**Comment by terrymanu** [comment]
Thank you for the attention, can the document[1] help you to get involve?

[1] https://shardingsphere.apache.org/community/en/contribute/

**Comment by terrymanu** [comment]
The document is the target of generated HTML which for deploy only, the source md file is in: https://github.com/apache/shardingsphere/tree/master/docs

**Comment by kimmking** [comment]
@AnshuTrivedi welcome to contribute this project.
Any thing about this project, we can discuss in:
-  dev@shardingsphere.apache.org  or
-  https://github.com/apache/shardingsphere/issues

**Comment by nuo-promise** [comment]
Can I Join in?

**Comment by kimmking** [comment]
@nuo-promise of course, every one can join in here.

**Comment by nuo-promise** [comment]
@kimmking  @terrymanu Thanks
