### ISSUE TITLE
the website & doc page's style so dark & distinctive?

### ISSUE THREAD

**Issue by xiangtao123** [shardingjdbc/sharding-jdbc-doc#548]
the website & doc page's style so dark & distinctive?

please analysis apache projects-list: 
http://www.apache.org/index.html#projects-list

Please keep the same level with industry.

1. The static BLACK background color makes people fell depressed.
2. Consistent with the traditional style. Learning from Others apache project website.

**Comment by terrymanu** [comment]
Any idea to improvement it?

**Comment by xiangtao123** [comment]
> Any idea to improvement it?

It look like switch color scheme. ref website: http://hudi.apache.org/

header part img:
![image](https://user-images.githubusercontent.com/3273673/104007715-56c35500-51e3-11eb-9fe7-49c54015b3ed.png)

header part css:
`background-color: #079fca !important;
color:#fff;
text-shadow:1px 1px 4px rgba(0,0,0,0.5);`

body part img:
![image](https://user-images.githubusercontent.com/3273673/104007797-765a7d80-51e3-11eb-8b53-e4a7d799b7ff.png)

body part css:
`background-color: #fff;
color:#222831;`

**Comment by xiangtao123** [comment]
cancel.
