### ISSUE TITLE
typo problem in official website

### ISSUE THREAD

**Issue by wjljack** [shardingjdbc/sharding-jdbc-doc#659]
link:[https://shardingsphere.apache.org/index_zh.html](https://shardingsphere.apache.org/index_zh.html)
```html
<meta property="og:title" content="Apache SharingSphere" /> //ShardingShpere
```

**Comment by Bhanu-code** [comment]
I have figured out where is this typo ,  I can fix this if author assign this issue to me.

**Comment by linghengqian** [comment]
> I have figured out where is this typo , I can fix this if author assign this issue to me.

CC @TeslaCN.

**Comment by linghengqian** [comment]
- Fixed by https://github.com/apache/shardingsphere-doc/pull/665.
