### ISSUE TITLE
Icons in are not showing in `https://shardingsphere.apache.org/community/**` pages

### ISSUE THREAD

**Issue by surjendu104** [shardingjdbc/sharding-jdbc-doc#740]
All the Icons in `https://shardingsphere.apache.org/community/**` are not showing.

![image](https://github.com/apache/shardingsphere-doc/assets/101238933/ffd4ae62-7b6e-4587-b424-3ccc4c6eac73)
![image](https://github.com/apache/shardingsphere-doc/assets/101238933/2c56c86d-be6b-49c1-9442-06817e0cb8c9)
![image](https://github.com/apache/shardingsphere-doc/assets/101238933/2d381e39-2616-4cb1-87a9-0aa927219076)

 Strep to reproduce : Go to [here](https://shardingsphere.apache.org/community/en/involved/)

cc: @linghengqian

**Comment by linghengqian** [comment]
- CC @Qianyi951015 @RaigorJiang . Is the failure of the icon to load caused by the new limitations of ASF, as in https://github.com/apache/shardingsphere/issues/30422 ?

**Comment by Qianyi951015** [comment]
> here

Hi, @linghengqian I don't think the limitations of ASF cause it. Everything looks good in my view for both English and Chinese versions.
![image](https://github.com/apache/shardingsphere-doc/assets/57847965/d854a676-2584-423d-834e-32c10cb34cad)
![image](https://github.com/apache/shardingsphere-doc/assets/57847965/4caec9d6-8388-4cf1-b463-fea696a24b46)

**Comment by linghengqian** [comment]
- From my perspective, this problem can be seen under Google Chrome 121.0.6167.85, whether it is the English document or the Chinese document. I'm not sure where the problem occurs.
- ![image](https://github.com/apache/shardingsphere-doc/assets/20187731/68036b29-1940-4d6c-8320-b0020180f3df)
- ![image](https://github.com/apache/shardingsphere-doc/assets/20187731/c5df5dcd-eb9f-429c-94dd-c9bc0278b3c5)

**Comment by Qianyi951015** [comment]
> * From my perspective, this problem can be seen under Google Chrome 121.0.6167.85, whether it is the English document or the Chinese document. I'm not sure where the problem occurs.
> * ![image](https://private-user-images.githubusercontent.com/20187731/314016248-68036b29-1940-4d6c-8320-b0020180f3df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDQ5OTQsIm5iZiI6MTcxMDg0NDY5NCwicGF0aCI6Ii8yMDE4NzczMS8zMTQwMTYyNDgtNjgwMzZiMjktMTk0MC00ZDZjLTgzMjAtYjAwMjAxODBmM2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEwMzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODExYjE2M2RhMzg0ZmYwMTQ3Y2M2ZjQ1NTFjNTU4YzBjYzgyNWVjMTY3NTVkNWQ5ZTAwN2YzMGM4MjdiYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n63IntIARcFEDywKmpsE-bDNWqISFKWeL_OYgh-ce8E)
> * ![image](https://private-user-images.githubusercontent.com/20187731/314017375-c5df5dcd-eb9f-429c-94dd-c9bc0278b3c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDQ5OTQsIm5iZiI6MTcxMDg0NDY5NCwicGF0aCI6Ii8yMDE4NzczMS8zMTQwMTczNzUtYzVkZjVkY2QtZWI5Zi00MjljLTk0ZGQtYzliYzAyNzhiM2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEwMzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZmUwN2EyMjhhM2RjOWM5NTk2ZDc2ZDQyMDBhZTRkOGIxNDU2YzQ5N2YyNGMyNzEwZjBlNmYzMTg3NjNjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.msQ8fL9FrbZBz7PU12bJqLfK9R5Oeqw9ms2_5PAgp7A)

My Google Chrome version is 122.0.6261.111 , could you please try updating your Google Chrome version and check if the problem still there?

**Comment by linghengqian** [comment]
> My Google Chrome version is 122.0.6261.111 , could you please try updating your Google Chrome version and check if the problem still there?

- I updated to Google Chrome 122.0.6261.128 and the issue persists.

**Comment by Qianyi951015** [comment]
> > My Google Chrome version is 122.0.6261.111 , could you please try updating your Google Chrome version and check if the problem still there?
> 
> * I updated to Google Chrome 122.0.6261.128 and the issue persists.

emmm...The only difference is that I am in New Zealand and you are in China. Is there any possibility that the Great Firewall of China causes it?

**Comment by surjendu104** [comment]
My chrome version : 122.0.6261.129
also same issue in Microsoft edge

**Comment by linghengqian** [comment]
- @Qianyi951015 I did additional testing on server hosts in different regions. There is a problem that the icon is not displayed when accessing https://shardingsphere.apache.org/community/en/involved/ from the server host at the following location.
   - Hong Kong, China
   - New Taipei, China
   - Singapore
   - Seoul, South Korea
   - Tokyo, Japan
   - Los Angeles, USA
   - Doddaballapura, India
   - Sydney, Australia
   - Frankfurt am Main, Germany
   - Paris, France
   - Warsaw, Poland
   - Amsterdam, Netherlands
   - Sevilla, Spain
   - Moscow, Russia
   - Reykjavík, Iceland
   - Copenhagen, Denmark
   - Toronto, Canada
   - London, UK
   - Bahçelievler, Türkiye
- Considering that I don't have a server host in New Zealand, I can't further verify why your side is showing normal.

**Comment by RaigorJiang** [comment]
@linghengqian @Qianyi951015 
The page I see is not abnormal, it seems to only happen on windows?

<img width="1330" alt="image" src="https://github.com/apache/shardingsphere-doc/assets/5668787/5e6f67f9-ba6e-4f0f-a0a9-f6ed13e31d67">

**Comment by linghengqian** [comment]
- @RaigorJiang I see this issue on both Windows 11 and Ubuntu 22.04.3. 

- Is this an AMD graphics driver specific issue?

**Comment by Qianyi951015** [comment]
> * @RaigorJiang I see this issue on both Windows 11 and Ubuntu 22.04.3.
> * Is this an AMD graphics driver specific issue?

Hi, @linghengqian I tried to browse the page on a Windows system with an Nvidia graphic card. The issue appeared. So I think the cause of this issue has nothing to do with the graphic driver.
![4641711021099_ pic](https://github.com/apache/shardingsphere-doc/assets/57847965/330ef88d-3f2a-4847-b822-1db0e81b4824)

**Comment by linghengqian** [comment]
- After #741 was merged, this document is back to normal on my device.

- @surjendu104 You can test it again.

**Comment by kid0510z** [comment]
@surjendu104 
This problem is caused by the damage of the font file. It is not a problem between the operating system or the browser. macOS does not load the font, but it displays it in a more friendly way (the display format is hidden icon), while windows has a small method. box, I have repaired the font file, please check it again (due to browser caching, it is recommended to view it in incognito mode). Pr:[link](https://github.com/apache/shardingsphere-doc/pull/741)

**Comment by surjendu104** [comment]
@linghengqian @kid0510z icons are showing now.

**Comment by RaigorJiang** [comment]
Thanks guys 👍

**Comment by Qianyi951015** [comment]
nice job
